In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [3]:
data=pd.read_csv(r"C:\Users\VAIO\Desktop\Dataset 2\Dataset\social.csv")

In [4]:
x=data.iloc[:,[2,3]].values
y=data.iloc[:,4].values


In [5]:
ss=StandardScaler()
scaled_x=ss.fit_transform(x)

d:\Users\VAIO\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
d:\Users\VAIO\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [6]:
x_train,x_test,y_train,y_test=train_test_split(scaled_x,y,test_size=0.25,random_state=0)

In [7]:
knc=KNeighborsClassifier( n_neighbors=5,weights='distance', algorithm='auto',leaf_size=30, p=2, metric='minkowski') 
knc.fit(x_train,y_train)
pred_y=knc.predict(x_test)
pred_y


array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [8]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [9]:
cm=confusion_matrix(y_test,pred_y)
cm

array([[64,  4],
       [ 3, 29]], dtype=int64)

In [15]:
(ss.fit_transform([[32,150000]])) #why not working
b=ss.fit_transform([[32,150000]])
b

array([[0., 0.]])

In [11]:
knc.predict([  [-0.54012675,  2.35674998]]) #same as above but it is working

array([1], dtype=int64)

In [12]:
prob=knc.predict_proba(x_test)#probability of gettind 0 and 1